### PR TITLE
fix mpl version

### PR DESCRIPTION
**Pull request by cxhernandez**
Trying to fix test failures in #55 and #54

### CODE REVIEW

**Comment by mpharrigan** [comment]
What's wrong with newer versions?

**Comment by mpharrigan** [comment]
Looks like it's using the wrong backend. Try setting this:

http://matplotlib.org/faq/environment_variables_faq.html#envvar-MPLBACKEND

**Comment by mpharrigan** [comment]
(to Agg)

**Comment by cxhernandez** [comment]
lol @ the windows instructions...

**Comment by mpharrigan** [comment]
In what way are you loling? They seem much simpler

**Comment by cxhernandez** [comment]
"Open the Control Panel...."

**Comment by mpharrigan** [comment]
Makes more sense than typing "export"

export

**Pull request closed without merging**
