### PR TITLE
No sideax

### PR DESCRIPTION
**Pull request by mpharrigan**
## Proposed Feature / Bug-Fix

This is my proposal for #52 

## Example Figure

```python
fig, ax = plt.subplots(figsize=(7,5))
msme.plot_trace(tica_traj[:,0], ax=ax)
```
msme

## PR Check-list

- ~~Example added~~
- ~~Tests added~~
- [x] Docs added
- [x] Changelog updated

### CODE REVIEW

**Comment by mpharrigan** [comment]
Does this make sense @cxhernandez ?

**Comment by cxhernandez** [comment]
Yeah! lgtm

**Comment by cxhernandez** [comment]
Could you rebase?

**Comment by mpharrigan** [comment]
rebased

**Comment by cxhernandez** [comment]
Thanks @mpharrigan!

**Pull request merged**
