### PR TITLE
initialize functionality

### PR DESCRIPTION
**Pull request by cxhernandez**
- [x] setup conda recipe
- [x] setup docs
- [x] msme color palette
- [x] msm plots
    - [x] raw versus msm counts
    - [x] timescale plots
    - [x] msm graph
- [x] tpt plots
    - [x] tpt graph

I'm thinking that most of these plotting functions should be called as follows:

```python
plot_func(msmb_obj, data=my_data, **kwargs)
```

so for instance, if I want to plot timescales I could do either:

```python
from msmbuilder.msm import MarkovStateModel
from msmexplorer import timescale_plot

plot_timescale(MarkovStateModel(), data=clustering_assignments)
```

or

```python
msm = MarkovStateModel()
msm.fit(clustering_assignments)
plot_timescale(msm)
```
cc @mpharrigan @msultan for more API brainstorming

### CODE REVIEW

**Comment by msultan** [comment]
Ty for getting this started @cxhernandez . imho the following api of plotting the fitted model makes the most sense. +1 for prefixing ```plot_``` to each plotting function, its very similar to mdtraj's ```compute_``` prefix 
```
msm = MarkovStateModel()
msm.fit(clustering_assignments)
plot_timescales(msm)
```

Also , could we add errorbars and movie makers to the list. I have been finding them rather useful.

**Comment by mpharrigan** [comment]
You should pick a license

**Comment by cxhernandez** [comment]
https://github.com/msmexplorer/msmexplorer/blob/master/LICENSE?

**Comment by mpharrigan** [comment]
oh lol. Is that the license you want tho? I think @rmcgibbo regretted picking it because lgpl doesn't make much sense for python because there is no "linking". I'd be in favor of a more permissive license

**Comment by cxhernandez** [comment]
MIT good?

**Comment by cxhernandez** [comment]
Not sure why tests are not running during `conda-build`....

**Comment by cxhernandez** [comment]
Okay merging this as a start!

**Comment by cxhernandez** [comment]
note: I could only get the tests to run locally when pinning conda-build to v1.17. Something is amuck in the latest version....

**Pull request merged**
